server:
  servlet.context-path: /orc-gs
  port: 8089

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:gs;LOCK_TIMEOUT=60000
    username: gs
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate #create, update, none and validate
  database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true #http://localhost:8089/orc-gs/h2-console


app:
  orchestrator-id: 123
  kafka:
    enabled: false
    bootstrapAddress: ${KAFKA_BOOTSTRAP_ADDRESS:http://localhost:9091}
    groupId: orchestrator-goods-storage
  agreement-client.type: no-mock
  delivery-client.type: no-mock
  notification-client.type: no-mock
  payment-client.type: no-mock
  product-client.type: no-mock