server.port: 8089


spring:
  datasource:
    driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:gs;LOCK_TIMEOUT=60000
    url: jdbc:h2:file:./db/goods-storage
    username: gs
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate #create, update, none and validate
  database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true #http://localhost:8080/gs/h2-console
